server:
  port: 7080
spring:
  application:
    name: MICRO_SERVICE-1
  data:
    mongodb:
      uri: mongodb://localhost:27017/productDatabase
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
      instance:
      hostname: localhost 