server:
  port: 7083
spring:
  application:
    name: MICRO_SERVICE-3
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
      instance:
      hostname: localhost 